language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"
matrix:
  allow_failures:
    - python: "2.6"
before_install:
  - pip install https://github.com/janbrohl/xmlcompare/archive/master.zip
  - pip install codecov
install: true
script: python runtests.py
after_success:
  - coverage run runtests.py
  - codecov
  
