language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"
before_install:
  - pip install codecov
install: true
script: coverage run runtests.py
after_success:
  - codecov
