language: python
cache: pip
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy3"
matrix:
  allow_failures:
    - python: "2.6"
before_install:
  - pip install codecov
  - pip install xmlcompare
install: true
script:
  - python setup.py test
  - python setup.py install
after_success:
  - coverage run -m unittest discover -p tests
  - codecov
  
